spring:
  datasource:
    url: jdbc:${DATABASE_URL}
    driver-class-name: org.postgresql.Driver

  data:
    redis:
      url: ${REDIS_URL}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true

server:
  port: ${PORT:8080}
  address: 0.0.0.0

springdoc:
  swagger-ui:
    path: /swagger

    flyway:
      enabled: true
      baseline-on-migrate: true
      locations: classpath:db/migration
      mail:
        host: smtp.gmail.com
        port:  587
        username: ${SPRING_MAIL_USERNAME:local@gmail.com}
        password: ${SPRING_MAIL_PASSWORD:local}
        properties:
          mail.smtp.auth: true
          mail.smtp.starttls.enable: true

          jwt:
            secret: ${JWT_SECRET}
            expiration: 86400000